# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lomaster/nesca4

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lomaster/nesca4

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lomaster/nesca4/CMakeFiles /home/lomaster/nesca4//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lomaster/nesca4/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nesca4

# Build rule for target.
nesca4: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nesca4
.PHONY : nesca4

# fast build rule for target.
nesca4/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/build
.PHONY : nesca4/fast

src/bruteforce.o: src/bruteforce.cc.o

.PHONY : src/bruteforce.o

# target to build an object file
src/bruteforce.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/src/bruteforce.cc.o
.PHONY : src/bruteforce.cc.o

src/bruteforce.i: src/bruteforce.cc.i

.PHONY : src/bruteforce.i

# target to preprocess a source file
src/bruteforce.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/src/bruteforce.cc.i
.PHONY : src/bruteforce.cc.i

src/bruteforce.s: src/bruteforce.cc.s

.PHONY : src/bruteforce.s

# target to generate assembly for a file
src/bruteforce.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/src/bruteforce.cc.s
.PHONY : src/bruteforce.cc.s

src/callbacks.o: src/callbacks.cc.o

.PHONY : src/callbacks.o

# target to build an object file
src/callbacks.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/src/callbacks.cc.o
.PHONY : src/callbacks.cc.o

src/callbacks.i: src/callbacks.cc.i

.PHONY : src/callbacks.i

# target to preprocess a source file
src/callbacks.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/src/callbacks.cc.i
.PHONY : src/callbacks.cc.i

src/callbacks.s: src/callbacks.cc.s

.PHONY : src/callbacks.s

# target to generate assembly for a file
src/callbacks.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/src/callbacks.cc.s
.PHONY : src/callbacks.cc.s

src/files.o: src/files.cc.o

.PHONY : src/files.o

# target to build an object file
src/files.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/src/files.cc.o
.PHONY : src/files.cc.o

src/files.i: src/files.cc.i

.PHONY : src/files.i

# target to preprocess a source file
src/files.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/src/files.cc.i
.PHONY : src/files.cc.i

src/files.s: src/files.cc.s

.PHONY : src/files.s

# target to generate assembly for a file
src/files.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/src/files.cc.s
.PHONY : src/files.cc.s

src/generation.o: src/generation.cc.o

.PHONY : src/generation.o

# target to build an object file
src/generation.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/src/generation.cc.o
.PHONY : src/generation.cc.o

src/generation.i: src/generation.cc.i

.PHONY : src/generation.i

# target to preprocess a source file
src/generation.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/src/generation.cc.i
.PHONY : src/generation.cc.i

src/generation.s: src/generation.cc.s

.PHONY : src/generation.s

# target to generate assembly for a file
src/generation.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/src/generation.cc.s
.PHONY : src/generation.cc.s

src/nesca4.o: src/nesca4.cc.o

.PHONY : src/nesca4.o

# target to build an object file
src/nesca4.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/src/nesca4.cc.o
.PHONY : src/nesca4.cc.o

src/nesca4.i: src/nesca4.cc.i

.PHONY : src/nesca4.i

# target to preprocess a source file
src/nesca4.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/src/nesca4.cc.i
.PHONY : src/nesca4.cc.i

src/nesca4.s: src/nesca4.cc.s

.PHONY : src/nesca4.s

# target to generate assembly for a file
src/nesca4.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/src/nesca4.cc.s
.PHONY : src/nesca4.cc.s

src/networktool.o: src/networktool.cc.o

.PHONY : src/networktool.o

# target to build an object file
src/networktool.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/src/networktool.cc.o
.PHONY : src/networktool.cc.o

src/networktool.i: src/networktool.cc.i

.PHONY : src/networktool.i

# target to preprocess a source file
src/networktool.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/src/networktool.cc.i
.PHONY : src/networktool.cc.i

src/networktool.s: src/networktool.cc.s

.PHONY : src/networktool.s

# target to generate assembly for a file
src/networktool.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/src/networktool.cc.s
.PHONY : src/networktool.cc.s

src/other.o: src/other.cc.o

.PHONY : src/other.o

# target to build an object file
src/other.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/src/other.cc.o
.PHONY : src/other.cc.o

src/other.i: src/other.cc.i

.PHONY : src/other.i

# target to preprocess a source file
src/other.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/src/other.cc.i
.PHONY : src/other.cc.i

src/other.s: src/other.cc.s

.PHONY : src/other.s

# target to generate assembly for a file
src/other.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/src/other.cc.s
.PHONY : src/other.cc.s

src/prints.o: src/prints.cc.o

.PHONY : src/prints.o

# target to build an object file
src/prints.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/src/prints.cc.o
.PHONY : src/prints.cc.o

src/prints.i: src/prints.cc.i

.PHONY : src/prints.i

# target to preprocess a source file
src/prints.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/src/prints.cc.i
.PHONY : src/prints.cc.i

src/prints.s: src/prints.cc.s

.PHONY : src/prints.s

# target to generate assembly for a file
src/prints.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/src/prints.cc.s
.PHONY : src/prints.cc.s

src/scanner.o: src/scanner.cc.o

.PHONY : src/scanner.o

# target to build an object file
src/scanner.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/src/scanner.cc.o
.PHONY : src/scanner.cc.o

src/scanner.i: src/scanner.cc.i

.PHONY : src/scanner.i

# target to preprocess a source file
src/scanner.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/src/scanner.cc.i
.PHONY : src/scanner.cc.i

src/scanner.s: src/scanner.cc.s

.PHONY : src/scanner.s

# target to generate assembly for a file
src/scanner.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/src/scanner.cc.s
.PHONY : src/scanner.cc.s

src/target.o: src/target.cc.o

.PHONY : src/target.o

# target to build an object file
src/target.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/src/target.cc.o
.PHONY : src/target.cc.o

src/target.i: src/target.cc.i

.PHONY : src/target.i

# target to preprocess a source file
src/target.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/src/target.cc.i
.PHONY : src/target.cc.i

src/target.s: src/target.cc.s

.PHONY : src/target.s

# target to generate assembly for a file
src/target.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/src/target.cc.s
.PHONY : src/target.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... nesca4"
	@echo "... src/bruteforce.o"
	@echo "... src/bruteforce.i"
	@echo "... src/bruteforce.s"
	@echo "... src/callbacks.o"
	@echo "... src/callbacks.i"
	@echo "... src/callbacks.s"
	@echo "... src/files.o"
	@echo "... src/files.i"
	@echo "... src/files.s"
	@echo "... src/generation.o"
	@echo "... src/generation.i"
	@echo "... src/generation.s"
	@echo "... src/nesca4.o"
	@echo "... src/nesca4.i"
	@echo "... src/nesca4.s"
	@echo "... src/networktool.o"
	@echo "... src/networktool.i"
	@echo "... src/networktool.s"
	@echo "... src/other.o"
	@echo "... src/other.i"
	@echo "... src/other.s"
	@echo "... src/prints.o"
	@echo "... src/prints.i"
	@echo "... src/prints.s"
	@echo "... src/scanner.o"
	@echo "... src/scanner.i"
	@echo "... src/scanner.s"
	@echo "... src/target.o"
	@echo "... src/target.i"
	@echo "... src/target.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

