# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lomaster/nesca4

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lomaster/nesca4

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lomaster/nesca4/CMakeFiles /home/lomaster/nesca4//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lomaster/nesca4/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nesca4

# Build rule for target.
nesca4: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nesca4
.PHONY : nesca4

# fast build rule for target.
nesca4/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/build
.PHONY : nesca4/fast

bruteforce.o: bruteforce.cc.o
.PHONY : bruteforce.o

# target to build an object file
bruteforce.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/bruteforce.cc.o
.PHONY : bruteforce.cc.o

bruteforce.i: bruteforce.cc.i
.PHONY : bruteforce.i

# target to preprocess a source file
bruteforce.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/bruteforce.cc.i
.PHONY : bruteforce.cc.i

bruteforce.s: bruteforce.cc.s
.PHONY : bruteforce.s

# target to generate assembly for a file
bruteforce.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/bruteforce.cc.s
.PHONY : bruteforce.cc.s

files.o: files.cc.o
.PHONY : files.o

# target to build an object file
files.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/files.cc.o
.PHONY : files.cc.o

files.i: files.cc.i
.PHONY : files.i

# target to preprocess a source file
files.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/files.cc.i
.PHONY : files.cc.i

files.s: files.cc.s
.PHONY : files.s

# target to generate assembly for a file
files.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/files.cc.s
.PHONY : files.cc.s

html.o: html.cc.o
.PHONY : html.o

# target to build an object file
html.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/html.cc.o
.PHONY : html.cc.o

html.i: html.cc.i
.PHONY : html.i

# target to preprocess a source file
html.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/html.cc.i
.PHONY : html.cc.i

html.s: html.cc.s
.PHONY : html.s

# target to generate assembly for a file
html.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/html.cc.s
.PHONY : html.cc.s

modules/hikvision.o: modules/hikvision.cc.o
.PHONY : modules/hikvision.o

# target to build an object file
modules/hikvision.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/modules/hikvision.cc.o
.PHONY : modules/hikvision.cc.o

modules/hikvision.i: modules/hikvision.cc.i
.PHONY : modules/hikvision.i

# target to preprocess a source file
modules/hikvision.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/modules/hikvision.cc.i
.PHONY : modules/hikvision.cc.i

modules/hikvision.s: modules/hikvision.cc.s
.PHONY : modules/hikvision.s

# target to generate assembly for a file
modules/hikvision.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/modules/hikvision.cc.s
.PHONY : modules/hikvision.cc.s

modules/negatives.o: modules/negatives.cc.o
.PHONY : modules/negatives.o

# target to build an object file
modules/negatives.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/modules/negatives.cc.o
.PHONY : modules/negatives.cc.o

modules/negatives.i: modules/negatives.cc.i
.PHONY : modules/negatives.i

# target to preprocess a source file
modules/negatives.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/modules/negatives.cc.i
.PHONY : modules/negatives.cc.i

modules/negatives.s: modules/negatives.cc.s
.PHONY : modules/negatives.s

# target to generate assembly for a file
modules/negatives.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/modules/negatives.cc.s
.PHONY : modules/negatives.cc.s

ncbase/base64.o: ncbase/base64.c.o
.PHONY : ncbase/base64.o

# target to build an object file
ncbase/base64.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncbase/base64.c.o
.PHONY : ncbase/base64.c.o

ncbase/base64.i: ncbase/base64.c.i
.PHONY : ncbase/base64.i

# target to preprocess a source file
ncbase/base64.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncbase/base64.c.i
.PHONY : ncbase/base64.c.i

ncbase/base64.s: ncbase/base64.c.s
.PHONY : ncbase/base64.s

# target to generate assembly for a file
ncbase/base64.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncbase/base64.c.s
.PHONY : ncbase/base64.c.s

ncbase/binary.o: ncbase/binary.c.o
.PHONY : ncbase/binary.o

# target to build an object file
ncbase/binary.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncbase/binary.c.o
.PHONY : ncbase/binary.c.o

ncbase/binary.i: ncbase/binary.c.i
.PHONY : ncbase/binary.i

# target to preprocess a source file
ncbase/binary.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncbase/binary.c.i
.PHONY : ncbase/binary.c.i

ncbase/binary.s: ncbase/binary.c.s
.PHONY : ncbase/binary.s

# target to generate assembly for a file
ncbase/binary.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncbase/binary.c.s
.PHONY : ncbase/binary.c.s

ncbase/getopt.o: ncbase/getopt.c.o
.PHONY : ncbase/getopt.o

# target to build an object file
ncbase/getopt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncbase/getopt.c.o
.PHONY : ncbase/getopt.c.o

ncbase/getopt.i: ncbase/getopt.c.i
.PHONY : ncbase/getopt.i

# target to preprocess a source file
ncbase/getopt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncbase/getopt.c.i
.PHONY : ncbase/getopt.c.i

ncbase/getopt.s: ncbase/getopt.c.s
.PHONY : ncbase/getopt.s

# target to generate assembly for a file
ncbase/getopt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncbase/getopt.c.s
.PHONY : ncbase/getopt.c.s

ncbase/json.o: ncbase/json.c.o
.PHONY : ncbase/json.o

# target to build an object file
ncbase/json.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncbase/json.c.o
.PHONY : ncbase/json.c.o

ncbase/json.i: ncbase/json.c.i
.PHONY : ncbase/json.i

# target to preprocess a source file
ncbase/json.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncbase/json.c.i
.PHONY : ncbase/json.c.i

ncbase/json.s: ncbase/json.c.s
.PHONY : ncbase/json.s

# target to generate assembly for a file
ncbase/json.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncbase/json.c.s
.PHONY : ncbase/json.c.s

ncsock/base.o: ncsock/base.c.o
.PHONY : ncsock/base.o

# target to build an object file
ncsock/base.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/base.c.o
.PHONY : ncsock/base.c.o

ncsock/base.i: ncsock/base.c.i
.PHONY : ncsock/base.i

# target to preprocess a source file
ncsock/base.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/base.c.i
.PHONY : ncsock/base.c.i

ncsock/base.s: ncsock/base.c.s
.PHONY : ncsock/base.s

# target to generate assembly for a file
ncsock/base.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/base.c.s
.PHONY : ncsock/base.c.s

ncsock/bruteforce.o: ncsock/bruteforce.c.o
.PHONY : ncsock/bruteforce.o

# target to build an object file
ncsock/bruteforce.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/bruteforce.c.o
.PHONY : ncsock/bruteforce.c.o

ncsock/bruteforce.i: ncsock/bruteforce.c.i
.PHONY : ncsock/bruteforce.i

# target to preprocess a source file
ncsock/bruteforce.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/bruteforce.c.i
.PHONY : ncsock/bruteforce.c.i

ncsock/bruteforce.s: ncsock/bruteforce.c.s
.PHONY : ncsock/bruteforce.s

# target to generate assembly for a file
ncsock/bruteforce.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/bruteforce.c.s
.PHONY : ncsock/bruteforce.c.s

ncsock/build_icmp6_pkt.o: ncsock/build_icmp6_pkt.c.o
.PHONY : ncsock/build_icmp6_pkt.o

# target to build an object file
ncsock/build_icmp6_pkt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/build_icmp6_pkt.c.o
.PHONY : ncsock/build_icmp6_pkt.c.o

ncsock/build_icmp6_pkt.i: ncsock/build_icmp6_pkt.c.i
.PHONY : ncsock/build_icmp6_pkt.i

# target to preprocess a source file
ncsock/build_icmp6_pkt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/build_icmp6_pkt.c.i
.PHONY : ncsock/build_icmp6_pkt.c.i

ncsock/build_icmp6_pkt.s: ncsock/build_icmp6_pkt.c.s
.PHONY : ncsock/build_icmp6_pkt.s

# target to generate assembly for a file
ncsock/build_icmp6_pkt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/build_icmp6_pkt.c.s
.PHONY : ncsock/build_icmp6_pkt.c.s

ncsock/build_icmp_pkt.o: ncsock/build_icmp_pkt.c.o
.PHONY : ncsock/build_icmp_pkt.o

# target to build an object file
ncsock/build_icmp_pkt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/build_icmp_pkt.c.o
.PHONY : ncsock/build_icmp_pkt.c.o

ncsock/build_icmp_pkt.i: ncsock/build_icmp_pkt.c.i
.PHONY : ncsock/build_icmp_pkt.i

# target to preprocess a source file
ncsock/build_icmp_pkt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/build_icmp_pkt.c.i
.PHONY : ncsock/build_icmp_pkt.c.i

ncsock/build_icmp_pkt.s: ncsock/build_icmp_pkt.c.s
.PHONY : ncsock/build_icmp_pkt.s

# target to generate assembly for a file
ncsock/build_icmp_pkt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/build_icmp_pkt.c.s
.PHONY : ncsock/build_icmp_pkt.c.s

ncsock/build_ip6_pkt.o: ncsock/build_ip6_pkt.c.o
.PHONY : ncsock/build_ip6_pkt.o

# target to build an object file
ncsock/build_ip6_pkt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/build_ip6_pkt.c.o
.PHONY : ncsock/build_ip6_pkt.c.o

ncsock/build_ip6_pkt.i: ncsock/build_ip6_pkt.c.i
.PHONY : ncsock/build_ip6_pkt.i

# target to preprocess a source file
ncsock/build_ip6_pkt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/build_ip6_pkt.c.i
.PHONY : ncsock/build_ip6_pkt.c.i

ncsock/build_ip6_pkt.s: ncsock/build_ip6_pkt.c.s
.PHONY : ncsock/build_ip6_pkt.s

# target to generate assembly for a file
ncsock/build_ip6_pkt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/build_ip6_pkt.c.s
.PHONY : ncsock/build_ip6_pkt.c.s

ncsock/build_ip_pkt.o: ncsock/build_ip_pkt.c.o
.PHONY : ncsock/build_ip_pkt.o

# target to build an object file
ncsock/build_ip_pkt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/build_ip_pkt.c.o
.PHONY : ncsock/build_ip_pkt.c.o

ncsock/build_ip_pkt.i: ncsock/build_ip_pkt.c.i
.PHONY : ncsock/build_ip_pkt.i

# target to preprocess a source file
ncsock/build_ip_pkt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/build_ip_pkt.c.i
.PHONY : ncsock/build_ip_pkt.c.i

ncsock/build_ip_pkt.s: ncsock/build_ip_pkt.c.s
.PHONY : ncsock/build_ip_pkt.s

# target to generate assembly for a file
ncsock/build_ip_pkt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/build_ip_pkt.c.s
.PHONY : ncsock/build_ip_pkt.c.s

ncsock/build_tcp.o: ncsock/build_tcp.c.o
.PHONY : ncsock/build_tcp.o

# target to build an object file
ncsock/build_tcp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/build_tcp.c.o
.PHONY : ncsock/build_tcp.c.o

ncsock/build_tcp.i: ncsock/build_tcp.c.i
.PHONY : ncsock/build_tcp.i

# target to preprocess a source file
ncsock/build_tcp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/build_tcp.c.i
.PHONY : ncsock/build_tcp.c.i

ncsock/build_tcp.s: ncsock/build_tcp.c.s
.PHONY : ncsock/build_tcp.s

# target to generate assembly for a file
ncsock/build_tcp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/build_tcp.c.s
.PHONY : ncsock/build_tcp.c.s

ncsock/build_tcp6_pkt.o: ncsock/build_tcp6_pkt.c.o
.PHONY : ncsock/build_tcp6_pkt.o

# target to build an object file
ncsock/build_tcp6_pkt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/build_tcp6_pkt.c.o
.PHONY : ncsock/build_tcp6_pkt.c.o

ncsock/build_tcp6_pkt.i: ncsock/build_tcp6_pkt.c.i
.PHONY : ncsock/build_tcp6_pkt.i

# target to preprocess a source file
ncsock/build_tcp6_pkt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/build_tcp6_pkt.c.i
.PHONY : ncsock/build_tcp6_pkt.c.i

ncsock/build_tcp6_pkt.s: ncsock/build_tcp6_pkt.c.s
.PHONY : ncsock/build_tcp6_pkt.s

# target to generate assembly for a file
ncsock/build_tcp6_pkt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/build_tcp6_pkt.c.s
.PHONY : ncsock/build_tcp6_pkt.c.s

ncsock/build_tcp_pkt.o: ncsock/build_tcp_pkt.c.o
.PHONY : ncsock/build_tcp_pkt.o

# target to build an object file
ncsock/build_tcp_pkt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/build_tcp_pkt.c.o
.PHONY : ncsock/build_tcp_pkt.c.o

ncsock/build_tcp_pkt.i: ncsock/build_tcp_pkt.c.i
.PHONY : ncsock/build_tcp_pkt.i

# target to preprocess a source file
ncsock/build_tcp_pkt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/build_tcp_pkt.c.i
.PHONY : ncsock/build_tcp_pkt.c.i

ncsock/build_tcp_pkt.s: ncsock/build_tcp_pkt.c.s
.PHONY : ncsock/build_tcp_pkt.s

# target to generate assembly for a file
ncsock/build_tcp_pkt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/build_tcp_pkt.c.s
.PHONY : ncsock/build_tcp_pkt.c.s

ncsock/build_udp6_pkt.o: ncsock/build_udp6_pkt.c.o
.PHONY : ncsock/build_udp6_pkt.o

# target to build an object file
ncsock/build_udp6_pkt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/build_udp6_pkt.c.o
.PHONY : ncsock/build_udp6_pkt.c.o

ncsock/build_udp6_pkt.i: ncsock/build_udp6_pkt.c.i
.PHONY : ncsock/build_udp6_pkt.i

# target to preprocess a source file
ncsock/build_udp6_pkt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/build_udp6_pkt.c.i
.PHONY : ncsock/build_udp6_pkt.c.i

ncsock/build_udp6_pkt.s: ncsock/build_udp6_pkt.c.s
.PHONY : ncsock/build_udp6_pkt.s

# target to generate assembly for a file
ncsock/build_udp6_pkt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/build_udp6_pkt.c.s
.PHONY : ncsock/build_udp6_pkt.c.s

ncsock/build_udp_pkt.o: ncsock/build_udp_pkt.c.o
.PHONY : ncsock/build_udp_pkt.o

# target to build an object file
ncsock/build_udp_pkt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/build_udp_pkt.c.o
.PHONY : ncsock/build_udp_pkt.c.o

ncsock/build_udp_pkt.i: ncsock/build_udp_pkt.c.i
.PHONY : ncsock/build_udp_pkt.i

# target to preprocess a source file
ncsock/build_udp_pkt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/build_udp_pkt.c.i
.PHONY : ncsock/build_udp_pkt.c.i

ncsock/build_udp_pkt.s: ncsock/build_udp_pkt.c.s
.PHONY : ncsock/build_udp_pkt.s

# target to generate assembly for a file
ncsock/build_udp_pkt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/build_udp_pkt.c.s
.PHONY : ncsock/build_udp_pkt.c.s

ncsock/dns.o: ncsock/dns.c.o
.PHONY : ncsock/dns.o

# target to build an object file
ncsock/dns.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/dns.c.o
.PHONY : ncsock/dns.c.o

ncsock/dns.i: ncsock/dns.c.i
.PHONY : ncsock/dns.i

# target to preprocess a source file
ncsock/dns.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/dns.c.i
.PHONY : ncsock/dns.c.i

ncsock/dns.s: ncsock/dns.c.s
.PHONY : ncsock/dns.s

# target to generate assembly for a file
ncsock/dns.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/dns.c.s
.PHONY : ncsock/dns.c.s

ncsock/exthdr.o: ncsock/exthdr.c.o
.PHONY : ncsock/exthdr.o

# target to build an object file
ncsock/exthdr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/exthdr.c.o
.PHONY : ncsock/exthdr.c.o

ncsock/exthdr.i: ncsock/exthdr.c.i
.PHONY : ncsock/exthdr.i

# target to preprocess a source file
ncsock/exthdr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/exthdr.c.i
.PHONY : ncsock/exthdr.c.i

ncsock/exthdr.s: ncsock/exthdr.c.s
.PHONY : ncsock/exthdr.s

# target to generate assembly for a file
ncsock/exthdr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/exthdr.c.s
.PHONY : ncsock/exthdr.c.s

ncsock/fast_send_tcp.o: ncsock/fast_send_tcp.c.o
.PHONY : ncsock/fast_send_tcp.o

# target to build an object file
ncsock/fast_send_tcp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/fast_send_tcp.c.o
.PHONY : ncsock/fast_send_tcp.c.o

ncsock/fast_send_tcp.i: ncsock/fast_send_tcp.c.i
.PHONY : ncsock/fast_send_tcp.i

# target to preprocess a source file
ncsock/fast_send_tcp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/fast_send_tcp.c.i
.PHONY : ncsock/fast_send_tcp.c.i

ncsock/fast_send_tcp.s: ncsock/fast_send_tcp.c.s
.PHONY : ncsock/fast_send_tcp.s

# target to generate assembly for a file
ncsock/fast_send_tcp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/fast_send_tcp.c.s
.PHONY : ncsock/fast_send_tcp.c.s

ncsock/fill_ip_raw.o: ncsock/fill_ip_raw.c.o
.PHONY : ncsock/fill_ip_raw.o

# target to build an object file
ncsock/fill_ip_raw.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/fill_ip_raw.c.o
.PHONY : ncsock/fill_ip_raw.c.o

ncsock/fill_ip_raw.i: ncsock/fill_ip_raw.c.i
.PHONY : ncsock/fill_ip_raw.i

# target to preprocess a source file
ncsock/fill_ip_raw.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/fill_ip_raw.c.i
.PHONY : ncsock/fill_ip_raw.c.i

ncsock/fill_ip_raw.s: ncsock/fill_ip_raw.c.s
.PHONY : ncsock/fill_ip_raw.s

# target to generate assembly for a file
ncsock/fill_ip_raw.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/fill_ip_raw.c.s
.PHONY : ncsock/fill_ip_raw.c.s

ncsock/ftp.o: ncsock/ftp.c.o
.PHONY : ncsock/ftp.o

# target to build an object file
ncsock/ftp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/ftp.c.o
.PHONY : ncsock/ftp.c.o

ncsock/ftp.i: ncsock/ftp.c.i
.PHONY : ncsock/ftp.i

# target to preprocess a source file
ncsock/ftp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/ftp.c.i
.PHONY : ncsock/ftp.c.i

ncsock/ftp.s: ncsock/ftp.c.s
.PHONY : ncsock/ftp.s

# target to generate assembly for a file
ncsock/ftp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/ftp.c.s
.PHONY : ncsock/ftp.c.s

ncsock/get_active_interface_name.o: ncsock/get_active_interface_name.c.o
.PHONY : ncsock/get_active_interface_name.o

# target to build an object file
ncsock/get_active_interface_name.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/get_active_interface_name.c.o
.PHONY : ncsock/get_active_interface_name.c.o

ncsock/get_active_interface_name.i: ncsock/get_active_interface_name.c.i
.PHONY : ncsock/get_active_interface_name.i

# target to preprocess a source file
ncsock/get_active_interface_name.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/get_active_interface_name.c.i
.PHONY : ncsock/get_active_interface_name.c.i

ncsock/get_active_interface_name.s: ncsock/get_active_interface_name.c.s
.PHONY : ncsock/get_active_interface_name.s

# target to generate assembly for a file
ncsock/get_active_interface_name.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/get_active_interface_name.c.s
.PHONY : ncsock/get_active_interface_name.c.s

ncsock/get_local_ip.o: ncsock/get_local_ip.c.o
.PHONY : ncsock/get_local_ip.o

# target to build an object file
ncsock/get_local_ip.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/get_local_ip.c.o
.PHONY : ncsock/get_local_ip.c.o

ncsock/get_local_ip.i: ncsock/get_local_ip.c.i
.PHONY : ncsock/get_local_ip.i

# target to preprocess a source file
ncsock/get_local_ip.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/get_local_ip.c.i
.PHONY : ncsock/get_local_ip.c.i

ncsock/get_local_ip.s: ncsock/get_local_ip.c.s
.PHONY : ncsock/get_local_ip.s

# target to generate assembly for a file
ncsock/get_local_ip.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/get_local_ip.c.s
.PHONY : ncsock/get_local_ip.c.s

ncsock/http.o: ncsock/http.c.o
.PHONY : ncsock/http.o

# target to build an object file
ncsock/http.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/http.c.o
.PHONY : ncsock/http.c.o

ncsock/http.i: ncsock/http.c.i
.PHONY : ncsock/http.i

# target to preprocess a source file
ncsock/http.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/http.c.i
.PHONY : ncsock/http.c.i

ncsock/http.s: ncsock/http.c.s
.PHONY : ncsock/http.s

# target to generate assembly for a file
ncsock/http.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/http.c.s
.PHONY : ncsock/http.c.s

ncsock/icmp_ping.o: ncsock/icmp_ping.c.o
.PHONY : ncsock/icmp_ping.o

# target to build an object file
ncsock/icmp_ping.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/icmp_ping.c.o
.PHONY : ncsock/icmp_ping.c.o

ncsock/icmp_ping.i: ncsock/icmp_ping.c.i
.PHONY : ncsock/icmp_ping.i

# target to preprocess a source file
ncsock/icmp_ping.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/icmp_ping.c.i
.PHONY : ncsock/icmp_ping.c.i

ncsock/icmp_ping.s: ncsock/icmp_ping.c.s
.PHONY : ncsock/icmp_ping.s

# target to generate assembly for a file
ncsock/icmp_ping.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/icmp_ping.c.s
.PHONY : ncsock/icmp_ping.c.s

ncsock/in_cksum.o: ncsock/in_cksum.c.o
.PHONY : ncsock/in_cksum.o

# target to build an object file
ncsock/in_cksum.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/in_cksum.c.o
.PHONY : ncsock/in_cksum.c.o

ncsock/in_cksum.i: ncsock/in_cksum.c.i
.PHONY : ncsock/in_cksum.i

# target to preprocess a source file
ncsock/in_cksum.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/in_cksum.c.i
.PHONY : ncsock/in_cksum.c.i

ncsock/in_cksum.s: ncsock/in_cksum.c.s
.PHONY : ncsock/in_cksum.s

# target to generate assembly for a file
ncsock/in_cksum.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/in_cksum.c.s
.PHONY : ncsock/in_cksum.c.s

ncsock/ip4_pseudoheader_check.o: ncsock/ip4_pseudoheader_check.c.o
.PHONY : ncsock/ip4_pseudoheader_check.o

# target to build an object file
ncsock/ip4_pseudoheader_check.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/ip4_pseudoheader_check.c.o
.PHONY : ncsock/ip4_pseudoheader_check.c.o

ncsock/ip4_pseudoheader_check.i: ncsock/ip4_pseudoheader_check.c.i
.PHONY : ncsock/ip4_pseudoheader_check.i

# target to preprocess a source file
ncsock/ip4_pseudoheader_check.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/ip4_pseudoheader_check.c.i
.PHONY : ncsock/ip4_pseudoheader_check.c.i

ncsock/ip4_pseudoheader_check.s: ncsock/ip4_pseudoheader_check.c.s
.PHONY : ncsock/ip4_pseudoheader_check.s

# target to generate assembly for a file
ncsock/ip4_pseudoheader_check.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/ip4_pseudoheader_check.c.s
.PHONY : ncsock/ip4_pseudoheader_check.c.s

ncsock/ip6_pseudoheader_check.o: ncsock/ip6_pseudoheader_check.c.o
.PHONY : ncsock/ip6_pseudoheader_check.o

# target to build an object file
ncsock/ip6_pseudoheader_check.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/ip6_pseudoheader_check.c.o
.PHONY : ncsock/ip6_pseudoheader_check.c.o

ncsock/ip6_pseudoheader_check.i: ncsock/ip6_pseudoheader_check.c.i
.PHONY : ncsock/ip6_pseudoheader_check.i

# target to preprocess a source file
ncsock/ip6_pseudoheader_check.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/ip6_pseudoheader_check.c.i
.PHONY : ncsock/ip6_pseudoheader_check.c.i

ncsock/ip6_pseudoheader_check.s: ncsock/ip6_pseudoheader_check.c.s
.PHONY : ncsock/ip6_pseudoheader_check.s

# target to generate assembly for a file
ncsock/ip6_pseudoheader_check.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/ip6_pseudoheader_check.c.s
.PHONY : ncsock/ip6_pseudoheader_check.c.s

ncsock/libdnet/addr.o: ncsock/libdnet/addr.c.o
.PHONY : ncsock/libdnet/addr.o

# target to build an object file
ncsock/libdnet/addr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/libdnet/addr.c.o
.PHONY : ncsock/libdnet/addr.c.o

ncsock/libdnet/addr.i: ncsock/libdnet/addr.c.i
.PHONY : ncsock/libdnet/addr.i

# target to preprocess a source file
ncsock/libdnet/addr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/libdnet/addr.c.i
.PHONY : ncsock/libdnet/addr.c.i

ncsock/libdnet/addr.s: ncsock/libdnet/addr.c.s
.PHONY : ncsock/libdnet/addr.s

# target to generate assembly for a file
ncsock/libdnet/addr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/libdnet/addr.c.s
.PHONY : ncsock/libdnet/addr.c.s

ncsock/libdnet/arp.o: ncsock/libdnet/arp.c.o
.PHONY : ncsock/libdnet/arp.o

# target to build an object file
ncsock/libdnet/arp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/libdnet/arp.c.o
.PHONY : ncsock/libdnet/arp.c.o

ncsock/libdnet/arp.i: ncsock/libdnet/arp.c.i
.PHONY : ncsock/libdnet/arp.i

# target to preprocess a source file
ncsock/libdnet/arp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/libdnet/arp.c.i
.PHONY : ncsock/libdnet/arp.c.i

ncsock/libdnet/arp.s: ncsock/libdnet/arp.c.s
.PHONY : ncsock/libdnet/arp.s

# target to generate assembly for a file
ncsock/libdnet/arp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/libdnet/arp.c.s
.PHONY : ncsock/libdnet/arp.c.s

ncsock/libdnet/eth.o: ncsock/libdnet/eth.c.o
.PHONY : ncsock/libdnet/eth.o

# target to build an object file
ncsock/libdnet/eth.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/libdnet/eth.c.o
.PHONY : ncsock/libdnet/eth.c.o

ncsock/libdnet/eth.i: ncsock/libdnet/eth.c.i
.PHONY : ncsock/libdnet/eth.i

# target to preprocess a source file
ncsock/libdnet/eth.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/libdnet/eth.c.i
.PHONY : ncsock/libdnet/eth.c.i

ncsock/libdnet/eth.s: ncsock/libdnet/eth.c.s
.PHONY : ncsock/libdnet/eth.s

# target to generate assembly for a file
ncsock/libdnet/eth.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/libdnet/eth.c.s
.PHONY : ncsock/libdnet/eth.c.s

ncsock/libdnet/ip.o: ncsock/libdnet/ip.c.o
.PHONY : ncsock/libdnet/ip.o

# target to build an object file
ncsock/libdnet/ip.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/libdnet/ip.c.o
.PHONY : ncsock/libdnet/ip.c.o

ncsock/libdnet/ip.i: ncsock/libdnet/ip.c.i
.PHONY : ncsock/libdnet/ip.i

# target to preprocess a source file
ncsock/libdnet/ip.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/libdnet/ip.c.i
.PHONY : ncsock/libdnet/ip.c.i

ncsock/libdnet/ip.s: ncsock/libdnet/ip.c.s
.PHONY : ncsock/libdnet/ip.s

# target to generate assembly for a file
ncsock/libdnet/ip.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/libdnet/ip.c.s
.PHONY : ncsock/libdnet/ip.c.s

ncsock/libdnet/ip6.o: ncsock/libdnet/ip6.c.o
.PHONY : ncsock/libdnet/ip6.o

# target to build an object file
ncsock/libdnet/ip6.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/libdnet/ip6.c.o
.PHONY : ncsock/libdnet/ip6.c.o

ncsock/libdnet/ip6.i: ncsock/libdnet/ip6.c.i
.PHONY : ncsock/libdnet/ip6.i

# target to preprocess a source file
ncsock/libdnet/ip6.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/libdnet/ip6.c.i
.PHONY : ncsock/libdnet/ip6.c.i

ncsock/libdnet/ip6.s: ncsock/libdnet/ip6.c.s
.PHONY : ncsock/libdnet/ip6.s

# target to generate assembly for a file
ncsock/libdnet/ip6.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/libdnet/ip6.c.s
.PHONY : ncsock/libdnet/ip6.c.s

ncsock/mt19937.o: ncsock/mt19937.c.o
.PHONY : ncsock/mt19937.o

# target to build an object file
ncsock/mt19937.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/mt19937.c.o
.PHONY : ncsock/mt19937.c.o

ncsock/mt19937.i: ncsock/mt19937.c.i
.PHONY : ncsock/mt19937.i

# target to preprocess a source file
ncsock/mt19937.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/mt19937.c.i
.PHONY : ncsock/mt19937.c.i

ncsock/mt19937.s: ncsock/mt19937.c.s
.PHONY : ncsock/mt19937.s

# target to generate assembly for a file
ncsock/mt19937.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/mt19937.c.s
.PHONY : ncsock/mt19937.c.s

ncsock/printhdr.o: ncsock/printhdr.c.o
.PHONY : ncsock/printhdr.o

# target to build an object file
ncsock/printhdr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/printhdr.c.o
.PHONY : ncsock/printhdr.c.o

ncsock/printhdr.i: ncsock/printhdr.c.i
.PHONY : ncsock/printhdr.i

# target to preprocess a source file
ncsock/printhdr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/printhdr.c.i
.PHONY : ncsock/printhdr.c.i

ncsock/printhdr.s: ncsock/printhdr.c.s
.PHONY : ncsock/printhdr.s

# target to generate assembly for a file
ncsock/printhdr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/printhdr.c.s
.PHONY : ncsock/printhdr.c.s

ncsock/read_packet.o: ncsock/read_packet.c.o
.PHONY : ncsock/read_packet.o

# target to build an object file
ncsock/read_packet.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/read_packet.c.o
.PHONY : ncsock/read_packet.c.o

ncsock/read_packet.i: ncsock/read_packet.c.i
.PHONY : ncsock/read_packet.i

# target to preprocess a source file
ncsock/read_packet.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/read_packet.c.i
.PHONY : ncsock/read_packet.c.i

ncsock/read_packet.s: ncsock/read_packet.c.s
.PHONY : ncsock/read_packet.s

# target to generate assembly for a file
ncsock/read_packet.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/read_packet.c.s
.PHONY : ncsock/read_packet.c.s

ncsock/rvi.o: ncsock/rvi.c.o
.PHONY : ncsock/rvi.o

# target to build an object file
ncsock/rvi.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/rvi.c.o
.PHONY : ncsock/rvi.c.o

ncsock/rvi.i: ncsock/rvi.c.i
.PHONY : ncsock/rvi.i

# target to preprocess a source file
ncsock/rvi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/rvi.c.i
.PHONY : ncsock/rvi.c.i

ncsock/rvi.s: ncsock/rvi.c.s
.PHONY : ncsock/rvi.s

# target to generate assembly for a file
ncsock/rvi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/rvi.c.s
.PHONY : ncsock/rvi.c.s

ncsock/send_frag_ip_packet.o: ncsock/send_frag_ip_packet.c.o
.PHONY : ncsock/send_frag_ip_packet.o

# target to build an object file
ncsock/send_frag_ip_packet.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/send_frag_ip_packet.c.o
.PHONY : ncsock/send_frag_ip_packet.c.o

ncsock/send_frag_ip_packet.i: ncsock/send_frag_ip_packet.c.i
.PHONY : ncsock/send_frag_ip_packet.i

# target to preprocess a source file
ncsock/send_frag_ip_packet.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/send_frag_ip_packet.c.i
.PHONY : ncsock/send_frag_ip_packet.c.i

ncsock/send_frag_ip_packet.s: ncsock/send_frag_ip_packet.c.s
.PHONY : ncsock/send_frag_ip_packet.s

# target to generate assembly for a file
ncsock/send_frag_ip_packet.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/send_frag_ip_packet.c.s
.PHONY : ncsock/send_frag_ip_packet.c.s

ncsock/send_icmp_packet.o: ncsock/send_icmp_packet.c.o
.PHONY : ncsock/send_icmp_packet.o

# target to build an object file
ncsock/send_icmp_packet.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/send_icmp_packet.c.o
.PHONY : ncsock/send_icmp_packet.c.o

ncsock/send_icmp_packet.i: ncsock/send_icmp_packet.c.i
.PHONY : ncsock/send_icmp_packet.i

# target to preprocess a source file
ncsock/send_icmp_packet.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/send_icmp_packet.c.i
.PHONY : ncsock/send_icmp_packet.c.i

ncsock/send_icmp_packet.s: ncsock/send_icmp_packet.c.s
.PHONY : ncsock/send_icmp_packet.s

# target to generate assembly for a file
ncsock/send_icmp_packet.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/send_icmp_packet.c.s
.PHONY : ncsock/send_icmp_packet.c.s

ncsock/send_ip4_packet.o: ncsock/send_ip4_packet.c.o
.PHONY : ncsock/send_ip4_packet.o

# target to build an object file
ncsock/send_ip4_packet.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/send_ip4_packet.c.o
.PHONY : ncsock/send_ip4_packet.c.o

ncsock/send_ip4_packet.i: ncsock/send_ip4_packet.c.i
.PHONY : ncsock/send_ip4_packet.i

# target to preprocess a source file
ncsock/send_ip4_packet.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/send_ip4_packet.c.i
.PHONY : ncsock/send_ip4_packet.c.i

ncsock/send_ip4_packet.s: ncsock/send_ip4_packet.c.s
.PHONY : ncsock/send_ip4_packet.s

# target to generate assembly for a file
ncsock/send_ip4_packet.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/send_ip4_packet.c.s
.PHONY : ncsock/send_ip4_packet.c.s

ncsock/send_ip6_packet.o: ncsock/send_ip6_packet.c.o
.PHONY : ncsock/send_ip6_packet.o

# target to build an object file
ncsock/send_ip6_packet.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/send_ip6_packet.c.o
.PHONY : ncsock/send_ip6_packet.c.o

ncsock/send_ip6_packet.i: ncsock/send_ip6_packet.c.i
.PHONY : ncsock/send_ip6_packet.i

# target to preprocess a source file
ncsock/send_ip6_packet.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/send_ip6_packet.c.i
.PHONY : ncsock/send_ip6_packet.c.i

ncsock/send_ip6_packet.s: ncsock/send_ip6_packet.c.s
.PHONY : ncsock/send_ip6_packet.s

# target to generate assembly for a file
ncsock/send_ip6_packet.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/send_ip6_packet.c.s
.PHONY : ncsock/send_ip6_packet.c.s

ncsock/send_ip_packet.o: ncsock/send_ip_packet.c.o
.PHONY : ncsock/send_ip_packet.o

# target to build an object file
ncsock/send_ip_packet.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/send_ip_packet.c.o
.PHONY : ncsock/send_ip_packet.c.o

ncsock/send_ip_packet.i: ncsock/send_ip_packet.c.i
.PHONY : ncsock/send_ip_packet.i

# target to preprocess a source file
ncsock/send_ip_packet.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/send_ip_packet.c.i
.PHONY : ncsock/send_ip_packet.c.i

ncsock/send_ip_packet.s: ncsock/send_ip_packet.c.s
.PHONY : ncsock/send_ip_packet.s

# target to generate assembly for a file
ncsock/send_ip_packet.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/send_ip_packet.c.s
.PHONY : ncsock/send_ip_packet.c.s

ncsock/send_ip_raw.o: ncsock/send_ip_raw.c.o
.PHONY : ncsock/send_ip_raw.o

# target to build an object file
ncsock/send_ip_raw.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/send_ip_raw.c.o
.PHONY : ncsock/send_ip_raw.c.o

ncsock/send_ip_raw.i: ncsock/send_ip_raw.c.i
.PHONY : ncsock/send_ip_raw.i

# target to preprocess a source file
ncsock/send_ip_raw.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/send_ip_raw.c.i
.PHONY : ncsock/send_ip_raw.c.i

ncsock/send_ip_raw.s: ncsock/send_ip_raw.c.s
.PHONY : ncsock/send_ip_raw.s

# target to generate assembly for a file
ncsock/send_ip_raw.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/send_ip_raw.c.s
.PHONY : ncsock/send_ip_raw.c.s

ncsock/send_tcp_packet.o: ncsock/send_tcp_packet.c.o
.PHONY : ncsock/send_tcp_packet.o

# target to build an object file
ncsock/send_tcp_packet.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/send_tcp_packet.c.o
.PHONY : ncsock/send_tcp_packet.c.o

ncsock/send_tcp_packet.i: ncsock/send_tcp_packet.c.i
.PHONY : ncsock/send_tcp_packet.i

# target to preprocess a source file
ncsock/send_tcp_packet.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/send_tcp_packet.c.i
.PHONY : ncsock/send_tcp_packet.c.i

ncsock/send_tcp_packet.s: ncsock/send_tcp_packet.c.s
.PHONY : ncsock/send_tcp_packet.s

# target to generate assembly for a file
ncsock/send_tcp_packet.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/send_tcp_packet.c.s
.PHONY : ncsock/send_tcp_packet.c.s

ncsock/send_udp_packet.o: ncsock/send_udp_packet.c.o
.PHONY : ncsock/send_udp_packet.o

# target to build an object file
ncsock/send_udp_packet.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/send_udp_packet.c.o
.PHONY : ncsock/send_udp_packet.c.o

ncsock/send_udp_packet.i: ncsock/send_udp_packet.c.i
.PHONY : ncsock/send_udp_packet.i

# target to preprocess a source file
ncsock/send_udp_packet.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/send_udp_packet.c.i
.PHONY : ncsock/send_udp_packet.c.i

ncsock/send_udp_packet.s: ncsock/send_udp_packet.c.s
.PHONY : ncsock/send_udp_packet.s

# target to generate assembly for a file
ncsock/send_udp_packet.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/send_udp_packet.c.s
.PHONY : ncsock/send_udp_packet.c.s

ncsock/set_flags.o: ncsock/set_flags.c.o
.PHONY : ncsock/set_flags.o

# target to build an object file
ncsock/set_flags.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/set_flags.c.o
.PHONY : ncsock/set_flags.c.o

ncsock/set_flags.i: ncsock/set_flags.c.i
.PHONY : ncsock/set_flags.i

# target to preprocess a source file
ncsock/set_flags.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/set_flags.c.i
.PHONY : ncsock/set_flags.c.i

ncsock/set_flags.s: ncsock/set_flags.c.s
.PHONY : ncsock/set_flags.s

# target to generate assembly for a file
ncsock/set_flags.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/set_flags.c.s
.PHONY : ncsock/set_flags.c.s

ncsock/set_tcp_flags.o: ncsock/set_tcp_flags.c.o
.PHONY : ncsock/set_tcp_flags.o

# target to build an object file
ncsock/set_tcp_flags.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/set_tcp_flags.c.o
.PHONY : ncsock/set_tcp_flags.c.o

ncsock/set_tcp_flags.i: ncsock/set_tcp_flags.c.i
.PHONY : ncsock/set_tcp_flags.i

# target to preprocess a source file
ncsock/set_tcp_flags.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/set_tcp_flags.c.i
.PHONY : ncsock/set_tcp_flags.c.i

ncsock/set_tcp_flags.s: ncsock/set_tcp_flags.c.s
.PHONY : ncsock/set_tcp_flags.s

# target to generate assembly for a file
ncsock/set_tcp_flags.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/set_tcp_flags.c.s
.PHONY : ncsock/set_tcp_flags.c.s

ncsock/smtp.o: ncsock/smtp.c.o
.PHONY : ncsock/smtp.o

# target to build an object file
ncsock/smtp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/smtp.c.o
.PHONY : ncsock/smtp.c.o

ncsock/smtp.i: ncsock/smtp.c.i
.PHONY : ncsock/smtp.i

# target to preprocess a source file
ncsock/smtp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/smtp.c.i
.PHONY : ncsock/smtp.c.i

ncsock/smtp.s: ncsock/smtp.c.s
.PHONY : ncsock/smtp.s

# target to generate assembly for a file
ncsock/smtp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/smtp.c.s
.PHONY : ncsock/smtp.c.s

ncsock/socket.o: ncsock/socket.c.o
.PHONY : ncsock/socket.o

# target to build an object file
ncsock/socket.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/socket.c.o
.PHONY : ncsock/socket.c.o

ncsock/socket.i: ncsock/socket.c.i
.PHONY : ncsock/socket.i

# target to preprocess a source file
ncsock/socket.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/socket.c.i
.PHONY : ncsock/socket.c.i

ncsock/socket.s: ncsock/socket.c.s
.PHONY : ncsock/socket.s

# target to generate assembly for a file
ncsock/socket.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/socket.c.s
.PHONY : ncsock/socket.c.s

ncsock/socks5.o: ncsock/socks5.c.o
.PHONY : ncsock/socks5.o

# target to build an object file
ncsock/socks5.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/socks5.c.o
.PHONY : ncsock/socks5.c.o

ncsock/socks5.i: ncsock/socks5.c.i
.PHONY : ncsock/socks5.i

# target to preprocess a source file
ncsock/socks5.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/socks5.c.i
.PHONY : ncsock/socks5.c.i

ncsock/socks5.s: ncsock/socks5.c.s
.PHONY : ncsock/socks5.s

# target to generate assembly for a file
ncsock/socks5.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/socks5.c.s
.PHONY : ncsock/socks5.c.s

ncsock/str_set_flags.o: ncsock/str_set_flags.c.o
.PHONY : ncsock/str_set_flags.o

# target to build an object file
ncsock/str_set_flags.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/str_set_flags.c.o
.PHONY : ncsock/str_set_flags.c.o

ncsock/str_set_flags.i: ncsock/str_set_flags.c.i
.PHONY : ncsock/str_set_flags.i

# target to preprocess a source file
ncsock/str_set_flags.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/str_set_flags.c.i
.PHONY : ncsock/str_set_flags.c.i

ncsock/str_set_flags.s: ncsock/str_set_flags.c.s
.PHONY : ncsock/str_set_flags.s

# target to generate assembly for a file
ncsock/str_set_flags.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/str_set_flags.c.s
.PHONY : ncsock/str_set_flags.c.s

ncsock/strbase.o: ncsock/strbase.c.o
.PHONY : ncsock/strbase.o

# target to build an object file
ncsock/strbase.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/strbase.c.o
.PHONY : ncsock/strbase.c.o

ncsock/strbase.i: ncsock/strbase.c.i
.PHONY : ncsock/strbase.i

# target to preprocess a source file
ncsock/strbase.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/strbase.c.i
.PHONY : ncsock/strbase.c.i

ncsock/strbase.s: ncsock/strbase.c.s
.PHONY : ncsock/strbase.s

# target to generate assembly for a file
ncsock/strbase.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/strbase.c.s
.PHONY : ncsock/strbase.c.s

ncsock/tcp_ping.o: ncsock/tcp_ping.c.o
.PHONY : ncsock/tcp_ping.o

# target to build an object file
ncsock/tcp_ping.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/tcp_ping.c.o
.PHONY : ncsock/tcp_ping.c.o

ncsock/tcp_ping.i: ncsock/tcp_ping.c.i
.PHONY : ncsock/tcp_ping.i

# target to preprocess a source file
ncsock/tcp_ping.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/tcp_ping.c.i
.PHONY : ncsock/tcp_ping.c.i

ncsock/tcp_ping.s: ncsock/tcp_ping.c.s
.PHONY : ncsock/tcp_ping.s

# target to generate assembly for a file
ncsock/tcp_ping.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/ncsock/tcp_ping.c.s
.PHONY : ncsock/tcp_ping.c.s

nesca4.o: nesca4.cc.o
.PHONY : nesca4.o

# target to build an object file
nesca4.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/nesca4.cc.o
.PHONY : nesca4.cc.o

nesca4.i: nesca4.cc.i
.PHONY : nesca4.i

# target to preprocess a source file
nesca4.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/nesca4.cc.i
.PHONY : nesca4.cc.i

nesca4.s: nesca4.cc.s
.PHONY : nesca4.s

# target to generate assembly for a file
nesca4.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/nesca4.cc.s
.PHONY : nesca4.cc.s

nescalog.o: nescalog.cc.o
.PHONY : nescalog.o

# target to build an object file
nescalog.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/nescalog.cc.o
.PHONY : nescalog.cc.o

nescalog.i: nescalog.cc.i
.PHONY : nescalog.i

# target to preprocess a source file
nescalog.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/nescalog.cc.i
.PHONY : nescalog.cc.i

nescalog.s: nescalog.cc.s
.PHONY : nescalog.s

# target to generate assembly for a file
nescalog.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/nescalog.cc.s
.PHONY : nescalog.cc.s

nescathread.o: nescathread.cc.o
.PHONY : nescathread.o

# target to build an object file
nescathread.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/nescathread.cc.o
.PHONY : nescathread.cc.o

nescathread.i: nescathread.cc.i
.PHONY : nescathread.i

# target to preprocess a source file
nescathread.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/nescathread.cc.i
.PHONY : nescathread.cc.i

nescathread.s: nescathread.cc.s
.PHONY : nescathread.s

# target to generate assembly for a file
nescathread.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/nescathread.cc.s
.PHONY : nescathread.cc.s

other.o: other.cc.o
.PHONY : other.o

# target to build an object file
other.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/other.cc.o
.PHONY : other.cc.o

other.i: other.cc.i
.PHONY : other.i

# target to preprocess a source file
other.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/other.cc.i
.PHONY : other.cc.i

other.s: other.cc.s
.PHONY : other.s

# target to generate assembly for a file
other.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/other.cc.s
.PHONY : other.cc.s

portscan.o: portscan.cc.o
.PHONY : portscan.o

# target to build an object file
portscan.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/portscan.cc.o
.PHONY : portscan.cc.o

portscan.i: portscan.cc.i
.PHONY : portscan.i

# target to preprocess a source file
portscan.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/portscan.cc.i
.PHONY : portscan.cc.i

portscan.s: portscan.cc.s
.PHONY : portscan.s

# target to generate assembly for a file
portscan.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/portscan.cc.s
.PHONY : portscan.cc.s

scanner.o: scanner.cc.o
.PHONY : scanner.o

# target to build an object file
scanner.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/scanner.cc.o
.PHONY : scanner.cc.o

scanner.i: scanner.cc.i
.PHONY : scanner.i

# target to preprocess a source file
scanner.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/scanner.cc.i
.PHONY : scanner.cc.i

scanner.s: scanner.cc.s
.PHONY : scanner.s

# target to generate assembly for a file
scanner.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/scanner.cc.s
.PHONY : scanner.cc.s

services.o: services.cc.o
.PHONY : services.o

# target to build an object file
services.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/services.cc.o
.PHONY : services.cc.o

services.i: services.cc.i
.PHONY : services.i

# target to preprocess a source file
services.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/services.cc.i
.PHONY : services.cc.i

services.s: services.cc.s
.PHONY : services.s

# target to generate assembly for a file
services.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/services.cc.s
.PHONY : services.cc.s

target.o: target.cc.o
.PHONY : target.o

# target to build an object file
target.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/target.cc.o
.PHONY : target.cc.o

target.i: target.cc.i
.PHONY : target.i

# target to preprocess a source file
target.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/target.cc.i
.PHONY : target.cc.i

target.s: target.cc.s
.PHONY : target.s

# target to generate assembly for a file
target.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nesca4.dir/build.make CMakeFiles/nesca4.dir/target.cc.s
.PHONY : target.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... nesca4"
	@echo "... bruteforce.o"
	@echo "... bruteforce.i"
	@echo "... bruteforce.s"
	@echo "... files.o"
	@echo "... files.i"
	@echo "... files.s"
	@echo "... html.o"
	@echo "... html.i"
	@echo "... html.s"
	@echo "... modules/hikvision.o"
	@echo "... modules/hikvision.i"
	@echo "... modules/hikvision.s"
	@echo "... modules/negatives.o"
	@echo "... modules/negatives.i"
	@echo "... modules/negatives.s"
	@echo "... ncbase/base64.o"
	@echo "... ncbase/base64.i"
	@echo "... ncbase/base64.s"
	@echo "... ncbase/binary.o"
	@echo "... ncbase/binary.i"
	@echo "... ncbase/binary.s"
	@echo "... ncbase/getopt.o"
	@echo "... ncbase/getopt.i"
	@echo "... ncbase/getopt.s"
	@echo "... ncbase/json.o"
	@echo "... ncbase/json.i"
	@echo "... ncbase/json.s"
	@echo "... ncsock/base.o"
	@echo "... ncsock/base.i"
	@echo "... ncsock/base.s"
	@echo "... ncsock/bruteforce.o"
	@echo "... ncsock/bruteforce.i"
	@echo "... ncsock/bruteforce.s"
	@echo "... ncsock/build_icmp6_pkt.o"
	@echo "... ncsock/build_icmp6_pkt.i"
	@echo "... ncsock/build_icmp6_pkt.s"
	@echo "... ncsock/build_icmp_pkt.o"
	@echo "... ncsock/build_icmp_pkt.i"
	@echo "... ncsock/build_icmp_pkt.s"
	@echo "... ncsock/build_ip6_pkt.o"
	@echo "... ncsock/build_ip6_pkt.i"
	@echo "... ncsock/build_ip6_pkt.s"
	@echo "... ncsock/build_ip_pkt.o"
	@echo "... ncsock/build_ip_pkt.i"
	@echo "... ncsock/build_ip_pkt.s"
	@echo "... ncsock/build_tcp.o"
	@echo "... ncsock/build_tcp.i"
	@echo "... ncsock/build_tcp.s"
	@echo "... ncsock/build_tcp6_pkt.o"
	@echo "... ncsock/build_tcp6_pkt.i"
	@echo "... ncsock/build_tcp6_pkt.s"
	@echo "... ncsock/build_tcp_pkt.o"
	@echo "... ncsock/build_tcp_pkt.i"
	@echo "... ncsock/build_tcp_pkt.s"
	@echo "... ncsock/build_udp6_pkt.o"
	@echo "... ncsock/build_udp6_pkt.i"
	@echo "... ncsock/build_udp6_pkt.s"
	@echo "... ncsock/build_udp_pkt.o"
	@echo "... ncsock/build_udp_pkt.i"
	@echo "... ncsock/build_udp_pkt.s"
	@echo "... ncsock/dns.o"
	@echo "... ncsock/dns.i"
	@echo "... ncsock/dns.s"
	@echo "... ncsock/exthdr.o"
	@echo "... ncsock/exthdr.i"
	@echo "... ncsock/exthdr.s"
	@echo "... ncsock/fast_send_tcp.o"
	@echo "... ncsock/fast_send_tcp.i"
	@echo "... ncsock/fast_send_tcp.s"
	@echo "... ncsock/fill_ip_raw.o"
	@echo "... ncsock/fill_ip_raw.i"
	@echo "... ncsock/fill_ip_raw.s"
	@echo "... ncsock/ftp.o"
	@echo "... ncsock/ftp.i"
	@echo "... ncsock/ftp.s"
	@echo "... ncsock/get_active_interface_name.o"
	@echo "... ncsock/get_active_interface_name.i"
	@echo "... ncsock/get_active_interface_name.s"
	@echo "... ncsock/get_local_ip.o"
	@echo "... ncsock/get_local_ip.i"
	@echo "... ncsock/get_local_ip.s"
	@echo "... ncsock/http.o"
	@echo "... ncsock/http.i"
	@echo "... ncsock/http.s"
	@echo "... ncsock/icmp_ping.o"
	@echo "... ncsock/icmp_ping.i"
	@echo "... ncsock/icmp_ping.s"
	@echo "... ncsock/in_cksum.o"
	@echo "... ncsock/in_cksum.i"
	@echo "... ncsock/in_cksum.s"
	@echo "... ncsock/ip4_pseudoheader_check.o"
	@echo "... ncsock/ip4_pseudoheader_check.i"
	@echo "... ncsock/ip4_pseudoheader_check.s"
	@echo "... ncsock/ip6_pseudoheader_check.o"
	@echo "... ncsock/ip6_pseudoheader_check.i"
	@echo "... ncsock/ip6_pseudoheader_check.s"
	@echo "... ncsock/libdnet/addr.o"
	@echo "... ncsock/libdnet/addr.i"
	@echo "... ncsock/libdnet/addr.s"
	@echo "... ncsock/libdnet/arp.o"
	@echo "... ncsock/libdnet/arp.i"
	@echo "... ncsock/libdnet/arp.s"
	@echo "... ncsock/libdnet/eth.o"
	@echo "... ncsock/libdnet/eth.i"
	@echo "... ncsock/libdnet/eth.s"
	@echo "... ncsock/libdnet/ip.o"
	@echo "... ncsock/libdnet/ip.i"
	@echo "... ncsock/libdnet/ip.s"
	@echo "... ncsock/libdnet/ip6.o"
	@echo "... ncsock/libdnet/ip6.i"
	@echo "... ncsock/libdnet/ip6.s"
	@echo "... ncsock/mt19937.o"
	@echo "... ncsock/mt19937.i"
	@echo "... ncsock/mt19937.s"
	@echo "... ncsock/printhdr.o"
	@echo "... ncsock/printhdr.i"
	@echo "... ncsock/printhdr.s"
	@echo "... ncsock/read_packet.o"
	@echo "... ncsock/read_packet.i"
	@echo "... ncsock/read_packet.s"
	@echo "... ncsock/rvi.o"
	@echo "... ncsock/rvi.i"
	@echo "... ncsock/rvi.s"
	@echo "... ncsock/send_frag_ip_packet.o"
	@echo "... ncsock/send_frag_ip_packet.i"
	@echo "... ncsock/send_frag_ip_packet.s"
	@echo "... ncsock/send_icmp_packet.o"
	@echo "... ncsock/send_icmp_packet.i"
	@echo "... ncsock/send_icmp_packet.s"
	@echo "... ncsock/send_ip4_packet.o"
	@echo "... ncsock/send_ip4_packet.i"
	@echo "... ncsock/send_ip4_packet.s"
	@echo "... ncsock/send_ip6_packet.o"
	@echo "... ncsock/send_ip6_packet.i"
	@echo "... ncsock/send_ip6_packet.s"
	@echo "... ncsock/send_ip_packet.o"
	@echo "... ncsock/send_ip_packet.i"
	@echo "... ncsock/send_ip_packet.s"
	@echo "... ncsock/send_ip_raw.o"
	@echo "... ncsock/send_ip_raw.i"
	@echo "... ncsock/send_ip_raw.s"
	@echo "... ncsock/send_tcp_packet.o"
	@echo "... ncsock/send_tcp_packet.i"
	@echo "... ncsock/send_tcp_packet.s"
	@echo "... ncsock/send_udp_packet.o"
	@echo "... ncsock/send_udp_packet.i"
	@echo "... ncsock/send_udp_packet.s"
	@echo "... ncsock/set_flags.o"
	@echo "... ncsock/set_flags.i"
	@echo "... ncsock/set_flags.s"
	@echo "... ncsock/set_tcp_flags.o"
	@echo "... ncsock/set_tcp_flags.i"
	@echo "... ncsock/set_tcp_flags.s"
	@echo "... ncsock/smtp.o"
	@echo "... ncsock/smtp.i"
	@echo "... ncsock/smtp.s"
	@echo "... ncsock/socket.o"
	@echo "... ncsock/socket.i"
	@echo "... ncsock/socket.s"
	@echo "... ncsock/socks5.o"
	@echo "... ncsock/socks5.i"
	@echo "... ncsock/socks5.s"
	@echo "... ncsock/str_set_flags.o"
	@echo "... ncsock/str_set_flags.i"
	@echo "... ncsock/str_set_flags.s"
	@echo "... ncsock/strbase.o"
	@echo "... ncsock/strbase.i"
	@echo "... ncsock/strbase.s"
	@echo "... ncsock/tcp_ping.o"
	@echo "... ncsock/tcp_ping.i"
	@echo "... ncsock/tcp_ping.s"
	@echo "... nesca4.o"
	@echo "... nesca4.i"
	@echo "... nesca4.s"
	@echo "... nescalog.o"
	@echo "... nescalog.i"
	@echo "... nescalog.s"
	@echo "... nescathread.o"
	@echo "... nescathread.i"
	@echo "... nescathread.s"
	@echo "... other.o"
	@echo "... other.i"
	@echo "... other.s"
	@echo "... portscan.o"
	@echo "... portscan.i"
	@echo "... portscan.s"
	@echo "... scanner.o"
	@echo "... scanner.i"
	@echo "... scanner.s"
	@echo "... services.o"
	@echo "... services.i"
	@echo "... services.s"
	@echo "... target.o"
	@echo "... target.i"
	@echo "... target.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

